name: Ruby

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
          echo 'Run test begin'
          echo 'event_name ${{ github.event_name }}'
          echo 'pull_request ${{ github.pull_request }}'
          echo 'action ${{ github.action }}'
          echo 'ref ${{ github.ref }}'
          echo 'Run test end'
