name: Build

on:
  pull_request:
    types: [opened, closed, edited]
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
          echo 'Run test begin'
          echo 'event_name ${{ github.event_name }}'
          echo 'pull_request ${{ github.pull_request }}'
          echo 'action ${{ github.action }}'
          echo 'ref ${{ github.ref }}'
          echo 'Run test end'

  deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    needs: build
    steps:
      - name: Deploy to Heroku
        run: |
          echo 'Run deploy Dev'
