name: Build

on:
  push:
  pull_request:
    types: [closed]
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
          echo 'Run build'
  deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    needs: build
    env:
      HEROKU_DEV_API_KEY: ${{ secrets.HEROKU_DEV_API_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 2.6.5
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.5
      - name: Deploy to Heroku
        run: |
          gem install dpl
          dpl --provider=heroku --app=huu-github-test --api-key=$HEROKU_DEV_API_KEY
