name: Ruby

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Try echo context
        run: |
          echo 'Run test begin'
          echo 'event_name ${{ github.event_name }}'
          echo 'pull_request ${{ github.pull_request }}'
          echo 'action ${{ github.action }}'
          echo 'ref ${{ github.ref }}'
          echo 'Run test end'
      - name: Deploy to Heroku
        run: |
          echo 'Run deploy'
