name: Build

on:
  push:
  pull_request:
    types: [closed]
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:12
        env:
          POSTGRES_USER: admin_helper_user
          POSTGRES_PASSWORD: 123
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 2.6.5
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.5
      - name: Install required apt packages and bundler
        run: |
          sudo apt-get -y install libpq-dev
          gem install bundler
      - name: Cache gems
        uses: actions/cache@v1
        env:
          cache-name: cache-gems
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
  deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    needs: build
    env:
      HEROKU_DEV_API_KEY: ${{ secrets.HEROKU_DEV_API_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 2.6.5
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.5
      - name: Deploy to Heroku
        run: |
          gem install dpl
          dpl --provider=heroku --app=huu-github-test --api-key=$HEROKU_DEV_API_KEY
