name: Build

on:
  push:
  pull_request:
    types: [closed]
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
          echo 'Should run on push new commit'
          echo 'Run test begin'
          echo 'event_name ${{ github.event_name }}'
          echo 'pull_request ${{ github.pull_request }}'
          echo 'action ${{ github.action }}'
          echo 'ref ${{ github.ref }}'
          echo 'Run test end'
  deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    needs: build
    env:
      HEROKU_DEV_API_KEY: ${{ secrets.HEROKU_DEV_API_KEY }}
    steps:
      - name: Deploy to Heroku
        run: |
          gem install dpl
          dpl --provider=heroku --app=huu-github-test --api-key=$HEROKU_DEV_API_KEY
