name: Ruby

on:
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    steps:
      - name: Deploy to Heroku
        run: |
          echo 'Run deploy'
